import { NextRequest, NextResponse } from "next/server";
import { Resend } from "resend";
import { ORG } from "@/config/org";

const TO_EMAIL = process.env.HMIS_REPORT_EMAIL ?? ORG.supportEmail;
const FROM_EMAIL = `CaseFlow Operations <${ORG.fromEmail}>`;

type HmisNote = {
  clientName: string;
  type: string;
  summary: string;
  staff: string;
  checkedAt?: string;
};

function buildEmailHtml(notes: HmisNote[], date: string): string {
  const formattedDate = new Date(date + "T12:00:00").toLocaleDateString("en-US", {
    weekday: "long",
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const rows = notes
    .map(
      (n) => `
    <tr style="border-bottom:1px solid #f1f5f9;">
      <td style="padding:12px 8px;font-weight:700;color:#0f172a;vertical-align:top;">${n.clientName}</td>
      <td style="padding:12px 8px;color:#475569;vertical-align:top;white-space:nowrap;">${n.type}</td>
      <td style="padding:12px 8px;color:#475569;vertical-align:top;">${n.staff}</td>
      <td style="padding:12px 8px;color:#0f172a;vertical-align:top;line-height:1.6;">${n.summary}</td>
    </tr>`
    )
    .join("");

  return `<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"/></head>
<body style="margin:0;padding:0;background:#f8fafc;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;">
  <div style="max-width:700px;margin:32px auto;background:#ffffff;border-radius:16px;overflow:hidden;box-shadow:0 4px 24px rgba(0,0,0,0.08);">
    
    <!-- Header -->
    <div style="background:linear-gradient(135deg,#0f766e,#0d9488);padding:32px 40px;">
      <p style="color:#ccfbf1;font-size:11px;font-weight:700;letter-spacing:0.15em;text-transform:uppercase;margin:0 0 8px;">T.O.O.LS INC · CaseFlow Operations</p>
      <h1 style="color:#ffffff;font-size:24px;font-weight:800;margin:0 0 4px;">End-of-Day HMIS Summary</h1>
      <p style="color:#99f6e4;font-size:14px;margin:0;">${formattedDate}</p>
    </div>

    <!-- Body -->
    <div style="padding:32px 40px;">
      <p style="color:#475569;font-size:15px;line-height:1.6;margin:0 0 24px;">
        All ${notes.length} case note${notes.length === 1 ? "" : "s"} for today have been marked as uploaded to 
        <strong style="color:#0f172a;">Clarity HMIS</strong>. This report is a record of the completed entries.
      </p>

      <table style="width:100%;border-collapse:collapse;font-size:14px;">
        <thead>
          <tr style="background:#f8fafc;">
            <th style="padding:10px 8px;text-align:left;color:#64748b;font-weight:700;font-size:11px;text-transform:uppercase;letter-spacing:0.08em;border-bottom:2px solid #e2e8f0;">Client (UID)</th>
            <th style="padding:10px 8px;text-align:left;color:#64748b;font-weight:700;font-size:11px;text-transform:uppercase;letter-spacing:0.08em;border-bottom:2px solid #e2e8f0;">Note Type</th>
            <th style="padding:10px 8px;text-align:left;color:#64748b;font-weight:700;font-size:11px;text-transform:uppercase;letter-spacing:0.08em;border-bottom:2px solid #e2e8f0;">Staff</th>
            <th style="padding:10px 8px;text-align:left;color:#64748b;font-weight:700;font-size:11px;text-transform:uppercase;letter-spacing:0.08em;border-bottom:2px solid #e2e8f0;">Narrative Summary</th>
          </tr>
        </thead>
        <tbody>${rows}</tbody>
      </table>

      <div style="margin-top:32px;padding:16px 20px;background:#f0fdf4;border-left:4px solid #22c55e;border-radius:8px;">
        <p style="margin:0;font-size:13px;color:#166534;font-weight:600;">
          ✓ ${notes.length} of ${notes.length} notes confirmed uploaded to Clarity HMIS
        </p>
        <p style="margin:4px 0 0;font-size:12px;color:#4ade80;">
          Auto-generated by CaseFlow · ${new Date().toLocaleTimeString("en-US", { hour: "2-digit", minute: "2-digit", timeZoneName: "short" })}
        </p>
      </div>
    </div>

    <!-- Footer -->
    <div style="padding:20px 40px;background:#f8fafc;border-top:1px solid #e2e8f0;">
      <p style="margin:0;font-size:12px;color:#94a3b8;text-align:center;">
        T.O.O.LS INC · CaseFlow Operations Portal · This is an automated end-of-day report.
      </p>
    </div>
  </div>
</body>
</html>`;
}

export async function POST(req: NextRequest) {
  const resend = new Resend(process.env.RESEND_API_KEY);

  const { notes, date } = (await req.json()) as { notes: HmisNote[]; date: string };

  if (!notes?.length || !date) {
    return NextResponse.json({ error: "notes and date are required" }, { status: 400 });
  }

  const formattedDate = new Date(date + "T12:00:00").toLocaleDateString("en-US", {
    weekday: "long",
    month: "long",
    day: "numeric",
    year: "numeric",
  });

  const { error } = await resend.emails.send({
    from: FROM_EMAIL,
    to: [TO_EMAIL],
    subject: `✓ HMIS EOD Report — ${formattedDate} (${notes.length} note${notes.length === 1 ? "" : "s"})`,
    html: buildEmailHtml(notes, date),
  });

  if (error) {
    console.error("HMIS EOD email error:", error);
    return NextResponse.json({ error: "Failed to send email" }, { status: 502 });
  }

  return NextResponse.json({ ok: true });
}
